In [ ]:
import requests
import pandas as pd

pd.set_option('display.max_columns', 300)
pd.set_option('display.max_rows', 15) #test
pd.set_option('display.float_format', '{:.2f}'.format)

In [4]:

API_BASE_VOLVO = "https://store.steampowered.com/appreviews/"

volvo_app_id = 730

Endpoint_volvo = f"{API_BASE_VOLVO}{volvo_app_id}" # подробности по игре

volvo_params = {
        "json": 1,
        "language": "all",
        "filter": "recent",
        "num_per_page": 100,
        "cursor": "*"
    }

response_volvo = requests.get(Endpoint_volvo, params=volvo_params)
print(response_volvo)
data_volvo = response_volvo.json()

print(type(data_volvo))
print(data_volvo.keys())

<Response [200]>
<class 'dict'>
dict_keys(['success', 'query_summary', 'reviews', 'cursor'])

In [5]:
print(data_volvo.keys())

dict_keys(['success', 'query_summary', 'reviews', 'cursor'])

In [6]:
volvo_df = pd.DataFrame(data_volvo['reviews'])

In [14]:
volvo_df

,recommendationid,author,language,review,timestamp_created,timestamp_updated,voted_up,votes_up,votes_funny,weighted_vote_score,comment_count,steam_purchase,received_for_free,refunded,written_during_early_access,primarily_steam_deck,app_release_date,reactions,hardware
0,220237890,"{'steamid': '76561199564706967', 'personaname'...",english,VERY FUN GAME,1773018911,1773018911,True,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
1,220237742,"{'steamid': '76561198357954126', 'personaname'...",russian,♥♥♥♥♥,1773018750,1773018750,False,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
2,220237730,"{'steamid': '76561199198269680', 'personaname'...",english,d,1773018735,1773018735,True,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
3,220237729,"{'steamid': '76561199575895071', 'personaname'...",latam,"Gran juego, suma puntos por inclusividad, hay ...",1773018735,1773018735,True,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
4,220237714,"{'steamid': '76561198962608511', 'personaname'...",english,5 Staps on CS\n1.Download CS \n2. Play 1k H\n3...,1773018722,1773018722,True,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,220230787,"{'steamid': '76561199316669200', 'personaname'...",turkish,fg,1773011731,1773011731,True,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
96,220230757,"{'steamid': '76561199221849181', 'personaname'...",english,Full of cheaters without a proper way of deali...,1773011714,1773011714,False,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
97,220230744,"{'steamid': '76561198739737840', 'personaname'...",russian,Запретите казахов,1773011701,1773011701,True,0,0,0.50,1,True,False,False,False,False,1345568400,[],NaN
98,220230627,"{'steamid': '76561198733329872', 'personaname'...",danish,csgo > cs2,1773011601,1773011601,True,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
99,220230465,"{'steamid': '76561198057703630', 'personaname'...",russian,"Помойка, состоящая из Токсичных школьников нап...",1773011430,1773011451,False,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN

In [ ]:
author_df = pd.json_normalize(volvo_df["author"])

In [15]:

# df = pd.concat([df.drop(columns=["author"]), author_df], axis=1)
volvo_df["timestamp_created"] = pd.to_datetime(volvo_df["timestamp_created"], unit="s")

In [17]:
volvo_df["timestamp_updated"] = pd.to_datetime(volvo_df["timestamp_updated"], unit="s")
volvo_df["app_release_date"] = pd.to_datetime(volvo_df["app_release_date"], unit="s")

DateParseError: year 1345568400 is out of range: 1345568400

In [16]:
volvo_df

,recommendationid,author,language,review,timestamp_created,timestamp_updated,voted_up,votes_up,votes_funny,weighted_vote_score,comment_count,steam_purchase,received_for_free,refunded,written_during_early_access,primarily_steam_deck,app_release_date,reactions,hardware
0,220237890,"{'steamid': '76561199564706967', 'personaname'...",english,VERY FUN GAME,2026-03-09 01:15:11,1773018911,True,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
1,220237742,"{'steamid': '76561198357954126', 'personaname'...",russian,♥♥♥♥♥,2026-03-09 01:12:30,1773018750,False,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
2,220237730,"{'steamid': '76561199198269680', 'personaname'...",english,d,2026-03-09 01:12:15,1773018735,True,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
3,220237729,"{'steamid': '76561199575895071', 'personaname'...",latam,"Gran juego, suma puntos por inclusividad, hay ...",2026-03-09 01:12:15,1773018735,True,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
4,220237714,"{'steamid': '76561198962608511', 'personaname'...",english,5 Staps on CS\n1.Download CS \n2. Play 1k H\n3...,2026-03-09 01:12:02,1773018722,True,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,220230787,"{'steamid': '76561199316669200', 'personaname'...",turkish,fg,2026-03-08 23:15:31,1773011731,True,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
96,220230757,"{'steamid': '76561199221849181', 'personaname'...",english,Full of cheaters without a proper way of deali...,2026-03-08 23:15:14,1773011714,False,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
97,220230744,"{'steamid': '76561198739737840', 'personaname'...",russian,Запретите казахов,2026-03-08 23:15:01,1773011701,True,0,0,0.50,1,True,False,False,False,False,1345568400,[],NaN
98,220230627,"{'steamid': '76561198733329872', 'personaname'...",danish,csgo > cs2,2026-03-08 23:13:21,1773011601,True,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN
99,220230465,"{'steamid': '76561198057703630', 'personaname'...",russian,"Помойка, состоящая из Токсичных школьников нап...",2026-03-08 23:10:30,1773011451,False,0,0,0.50,0,True,False,False,False,False,1345568400,[],NaN

In [12]:
author_df

,steamid,personaname,persona_status,profile_url,num_games_owned,num_reviews,playtime_forever,playtime_last_two_weeks,playtime_at_review,last_played,avatar
0,76561199564706967,cap,offline,https://steamcommunity.com/profiles/7656119956...,0,1,6522,90,6492,1773020693,fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb
1,76561198357954126,ONESHKA,offline,https://steamcommunity.com/id/Gogofoshsabb/,0,1,123680,3598,123680,1773018731,5578730f966daa4131be4b64419a69bafad6f31b
2,76561199198269680,churaq kubi,offline,https://steamcommunity.com/profiles/7656119919...,0,1,8414,1469,8414,1773016239,3f0333b9a7cd126c017911e990050f7ba2f0b980
3,76561199575895071,Sway!,online,https://steamcommunity.com/profiles/7656119957...,45,1,14745,540,14745,1772750080,43df12b6a1175e6139eabd82416e841e449c7f6a
4,76561198962608511,[ASAP] B1ber,offline,https://steamcommunity.com/profiles/7656119896...,76,3,74897,4940,74876,1773019131,abbb977ff48895d204856f92214b01177d35eaac
5,76561197983839937,<CSVet>,online,https://steamcommunity.com/profiles/7656119798...,0,2,21535,0,21535,1708226803,f92b57b1006b4d805e0dc416c14bf3e8ebad8951
6,76561198740600763,Neuro_ooo,online,https://steamcommunity.com/profiles/7656119874...,9,1,3167,850,3137,1773019306,ad429d6be4c0fb86b2fc45fbe26682ec8e83cad5
7,76561199522542837,Shadew,offline,https://steamcommunity.com/profiles/7656119952...,38,3,6516,501,6478,1773020625,82b54986ffd37d7d8448ca9586571904f0e3a9f0
8,76561199467143263,( Murad ),online,https://steamcommunity.com/profiles/7656119946...,0,1,2755,90,2725,1773019413,799c06eb77f6cb1887dcd6b777a22ec2ab586401
9,76561198451518521,Xz,online,https://steamcommunity.com/profiles/7656119845...,7,1,7051,1920,7051,1772995201,c687a19eb863b88967b1cc9a2fcc015149fa733b
10,76561198895145380,DeltaBravo55,online,https://steamcommunity.com/profiles/7656119889...,0,1,29260,908,29260,1773018223,91817c175f8480fee80f90f5d2e8a638901c819c
11,76561198085689254,Syrex,in-game,https://steamcommunity.com/profiles/7656119808...,95,3,10855,4641,10855,1773017700,cc82766340ebb6610b65d25b450a78cd39d55733
12,76561198334772650,Cogollo,offline,https://steamcommunity.com/profiles/7656119833...,0,3,93447,2486,93447,1773019374,99451e6f45c5af95ca25860fdd9049753b4551b0
13,76561198754801526,d1kxar,offline,https://steamcommunity.com/profiles/7656119875...,15,2,11873,2060,11873,1773017946,dd19379620b4539214f87cb1d7d8954d8013b64e
14,76561199027422987,Tomskaa,offline,https://steamcommunity.com/profiles/7656119902...,0,1,21581,655,21557,1773018890,2de8dfc0dff152b4562376550761d47231279ae9
15,76561199171265414,gin de 10,offline,https://steamcommunity.com/profiles/7656119917...,35,3,16330,422,16330,1773017719,b2dc8c8fabc9c245f165d47a6e51d6a96dbac637
16,76561198734161778,1zzzy,online,https://steamcommunity.com/profiles/7656119873...,0,1,423,472,423,1773016854,ab2d20c1ecb3106d17b1ed4dc9e35b6162fa8680
17,76561199506317097,HOMSHURBO,offline,https://steamcommunity.com/profiles/7656119950...,6,1,36285,178,36285,1772279060,867ff2f3a2cfdc8dfb2c68ccde4e1e67c51be801
18,76561199130647190,Kazuya Mishima,offline,https://steamcommunity.com/profiles/7656119913...,1,4,986,157,986,1772553411,ce3b3d745cea61662c643e8e58f7904311bd8c29
19,76561198735921547,☯ W H I T E ☯,in-game,https://steamcommunity.com/profiles/7656119873...,3,1,664,664,646,1773017747,a46edc2186d1fad0970592ff397cf02dc0354111
20,76561199810621845,vekZzz,offline,https://steamcommunity.com/profiles/7656119981...,0,1,8728,81,8728,1772804490,ea9359634aae49803144e9cbad8990f36e8c6126
21,76561199047008433,Daewoo Matiz,offline,https://steamcommunity.com/profiles/7656119904...,1,1,49871,141,49841,1773019620,fe50f19011d98ebf068ed25b5b378b530f160c74
22,76561198731443303,Qatar Energy,in-game,https://steamcommunity.com/profiles/7656119873...,3,1,1779,1779,1719,1773019976,1b0753e7134444c270d8736db78c219a5038e099
23,76561198752765560,$WeetB,offline,https://steamcommunity.com/id/Mr_steeve/,7,1,3855,1226,3812,1773019750,5861a2b7a332ccdefe71e0ce1aa63b9648aa5914
24,76561198731168214,image,offline,https://steamcommunity.com/profiles/7656119873...,0,1,489,489,429,1773020687,e15f840bcca3de70331c4cdfbc5d93cab9deca01
25,76561198426811185,patak,online,https://steamcommunity.com/id/patakcs/,0,1,1144,1144,1084,1773020566,1bbecc659b8dcfedaff95b0c361e40a4b313fb54
26,76561199835966279,rekt🔥,offline,https://steamcommunity.com/profiles/7656119983...,2,2,21338,4369,21338,1773016609,01d5619cb6c8c903027727e0877d3442ef9a23df
27,76561198413672931,Force_Edge,online,https://steamcommunity.com/profiles/7656119841...,0,1,9929,1619,9869,1773019876,b9a833a1d876f16978e7a16b9ca01a3ffd0e0a8a
28,76561198744541314,Cyber,offline,https://steamcommunity.com/profiles/7656119874...,10,1,1694,1583,1694,1773004934,dff52c37f0bbf86c898455ac153db6d92543c34a
29,76561198761886440,scotty kilmer,offline,https://steamcommunity.com/profiles/7656119876...,4,1,8934,1304,8901,1773018837,536874c56ec38a9d16970d5f406cef3b72789b8a
30,76561199115563261,ramen noodle,online,https://steamcommunity.com/id/mrbeans21/,32,1,6323,1056,6257,1773019653,114a07a60db49281d493dfd76391324d011010dc
31,76561198746482224,pojebany skurveny cigoši 🤬,offline,https://steamcommunity.com/profiles/7656119874...,1,1,10071,3650,10071,1773015725,4a9284d7e3038b3c969331a36cacc13d5b999905
32,76561199018384229,Ingemar,offline,https://steamcommunity.com/profiles/7656119901...,0,9,19289,1579,19289,1773014811,ea91ba7f0a10d484913bc92a3140d13ba47337d1
33,76561199833786992,lAZY|ЧУХОБЛОХ,in-game,https://steamcommunity.com/profiles/7656119983...,20,1,40026,3812,39966,1773020027,41957e12a0a8523ff1e8e1e87a12b629a68818bd
34,76561199618905252,♥빌어먹을 공주♥,online,https://steamcommunity.com/id/serka63/,0,1,6177,573,6100,1773019640,dff3d2d2ffed852c06ad66af5326418dbc3bc290
35,76561198790574152,BadFinger69,offline,https://steamcommunity.com/profiles/7656119879...,10,1,8332,781,8306,1773017897,1dd5db23fad754fac46c0323bde59754f343547d
36,76561198215264275,WeaseL,offline,https://steamcommunity.com/profiles/7656119821...,37,1,111815,748,111780,1773018264,2e692a894e40ad57a224875bad5eea8983581e3a
37,76561198783659430,sonnet,offline,https://steamcommunity.com/profiles/7656119878...,8,1,11959,912,11918,1773018545,f445b16a63929e6e2d9e60355389dda9d642c19e
38,76561199767562921,ุ,offline,https://steamcommunity.com/profiles/7656119976...,0,1,2705,521,2645,1773019495,318e5d561e9c3c8d7f3b05f4ef8ff7804672efc3
39,76561198300819340,pxmato,offline,https://steamcommunity.com/id/pxmato/,33,1,63737,1891,63737,1773014317,e24f6356ebee1533ab84affc0e3cdaf1ffb7984b
40,76561199843212247,XR,offline,https://steamcommunity.com/profiles/7656119984...,0,1,3646,1906,3630,1773016782,8196f7ea21811a83b5b7f902552116d47f348081
41,76561199541712260,Zuìrén,offline,https://steamcommunity.com/profiles/7656119954...,30,1,58528,3428,58528,1773009792,0a76ebf69efdc0c9de77b3370838e9a75a5299af
42,76561199802204517,Spider brad,offline,https://steamcommunity.com/profiles/7656119980...,3,1,19929,3547,19879,1773020687,daf680befd4758e817669623dac206e7476d0b6f
43,76561199094374223,Cluckss,offline,https://steamcommunity.com/profiles/7656119909...,0,1,9675,496,9675,1773004706,f9b840887f4449ff9864793ba05589765cbb6a05
44,76561199831097078,REG,offline,https://steamcommunity.com/profiles/7656119983...,2,1,13886,2261,13884,1773015794,1618474e6d6f8fb46dcb27ab035c4b075e183253
45,76561197985321476,Fael91,online,https://steamcommunity.com/profiles/7656119798...,43,2,58879,955,58849,1773017396,5c5468120b5e3e2786241437d2eaa54c7cdbfcc5
46,76561199016173400,mentalmente insano,offline,https://steamcommunity.com/id/jevrton/,158,5,17665,857,17605,1773019144,6f12683ca555ea76da52cff8267c9a71882162c5
47,76561199219280974,vz?,offline,https://steamcommunity.com/profiles/7656119921...,19,1,29724,425,29724,1772888406,9e1946ab04ac18c81142e074fe949f61a9b71bc6
48,76561198832052021,Stechk1n,offline,https://steamcommunity.com/profiles/7656119883...,0,1,15363,1454,15363,1773000225,a9ef804960d4e8b76e5c2cc3dfa3fd5c0b56c00a
49,76561199000823598,LØW,offline,https://steamcommunity.com/profiles/7656119900...,0,1,10159,5361,10105,1773017508,62fe4639489a0b210841f8a7c05fecf598f585e1
50,76561199036544880,SPONGEBOB,offline,https://steamcommunity.com/id/titaniktr/,6,1,10503,424,10446,1773017811,ce2d51d4fd599c3a136762c446aa6ed017fa93ca
51,76561199507242270,Polina,offline,https://steamcommunity.com/id/yeahm8r/,0,1,11704,2913,11608,1773020505,487a6f6e2a78afeab718b22ac70fab6de3e698fc
52,76561199017378509,☣ CHERNOBYL ☣,offline,https://steamcommunity.com/profiles/7656119901...,32,1,17546,5285,17544,1773018063,14fa45d90d1774068441651602af9b2de61890b4
53,76561199505205358,Messi SKINS,offline,https://steamcommunity.com/profiles/7656119950...,1,1,31086,1014,31057,1773016672,5fe682f2e29d1510e39d59bdfc569b336d0d7c43
54,76561199250001685,❤︎blya blya blya❤,offline,https://steamcommunity.com/profiles/7656119925...,0,3,85437,481,85437,1772996029,3762a1e6b698eb865683ed581550b3c2afb56624
55,76561199505756139,bvbvbvbudvbv,offline,https://steamcommunity.com/id/qweeface/,8,1,12393,1399,12393,1773009979,a93d546d9793987d475e86111296e9135d28e03d
56,76561199187216717,fefe,offline,https://steamcommunity.com/profiles/7656119918...,0,1,6591,1699,6571,1773014934,fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb
57,76561198784575029,SARbaz,offline,https://steamcommunity.com/profiles/7656119878...,0,1,5863,1349,5863,1772970701,e9d97f9a6bfa7ed126eae6f0cf7048734af41531
58,76561199497299216,TOMAKO,in-game,https://steamcommunity.com/profiles/7656119949...,363,5,40276,90,40186,1773020010,01556f9d80c57a0588a9d0f132d50cb815cd1b22
59,76561198849484798,s0us@,offline,https://steamcommunity.com/profiles/7656119884...,1,1,185975,1200,185975,1773014053,3aca13bd9ef9d637821d4af45fdd966cfe45c64e
60,76561199229653458,miheyfalkoff,online,https://steamcommunity.com/id/miheyfalkoff/,22,1,61254,3569,61254,1773014171,92ef9067a3b2af31647a47783cf46d03cadc9e9b
61,76561198740048386,Apple,online,https://steamcommunity.com/profiles/7656119874...,0,1,1794,280,1682,1773019637,5bd7fa5a8636e80e3e697b2dc8f75948734e0f40
62,76561199803191386,Медицина СССР,offline,https://steamcommunity.com/profiles/7656119980...,43,2,3514,45,3514,1772833558,8af3c5f33fd70d90e45f824051dfabd86779347b
63,76561198364474933,lous,offline,https://steamcommunity.com/id/soulboxing/,0,1,43352,1138,43352,1773013902,36282674bff458a9439e8b104063735342e468ea
64,76561199613122828,Ripper,offline,https://steamcommunity.com/profiles/7656119961...,1,1,78649,12,78637,1773018791,1c1b72cf645494d19ad14bf082fdedd805219703
65,76561198754783774,uchiha_fadi,offline,https://steamcommunity.com/profiles/7656119875...,0,1,9008,1979,8958,1773018125,90566b10e89835bd9eb8f1ff9b66ec9d7192532b
66,76561198760222212,djab3U,offline,https://steamcommunity.com/profiles/7656119876...,3,1,10776,1776,10776,1772929675,99b90b287e72da329c6f57f14f47ed77ca580a46
67,76561199564030911,svyzzu,offline,https://steamcommunity.com/profiles/7656119956...,0,2,12240,986,12240,1772918720,0bd576fb0228e0e4d33317ef58b32f12f71e521b
68,76561199225053422,f4sterZ,in-game,https://steamcommunity.com/id/f4sterZ/,1,1,9917,1346,9856,1773018968,2de4fe2cf9d61331bcb3eb279ce515d78c9ef456
69,76561197960628822,MAD.HATT3R,offline,https://steamcommunity.com/profiles/7656119796...,9,1,17983,18005,17949,1773015519,660a22a8f93e4b00aad2621558fa78bd4fddbb09
70,76561199235041655,uliseASY,offline,https://steamcommunity.com/profiles/7656119923...,0,8,4471,0,4471,1771611755,6709eb8971f4c185c9b8208e54518e879effea77
71,76561198383648864,Jo0hnn,online,https://steamcommunity.com/profiles/7656119838...,7,1,7124,130,7105,1773014690,ac97441db505e33f1d3aabc2d12071cd1602f32a
72,76561198777927653,βøśś,offline,https://steamcommunity.com/profiles/7656119877...,5,2,105706,12995,105648,1773016030,4abf8ca459956de692d5cd0a7ca8e89ea67b7964
73,76561198755382043,d1aneSʰᵐʰᵃˢ♡,offline,https://steamcommunity.com/profiles/7656119875...,0,1,13356,2305,13356,1773012788,9f2f56bddffa4dead934589609af2020c83d2011
74,76561198752743610,Asukaru,offline,https://steamcommunity.com/profiles/7656119875...,11,1,6039,2796,6039,1773013443,181025648d801aa9bce17fbd7479459df5fc242a
75,76561199683693234,k1lljoyz,offline,https://steamcommunity.com/id/psychoshoke/,15,3,13131,2064,13131,1773013071,d64315a00f706ee60fc97a13ecb6c42f19d473b6
76,76561198737286209,emzet80,offline,https://steamcommunity.com/profiles/7656119873...,1,1,2306,2274,2303,1773013624,fb072af656f9e4a9e40949d60a48b560f182e04e
77,76561199760071775,Nezoow,offline,https://steamcommunity.com/profiles/7656119976...,0,1,16482,1724,16370,1773017049,b7224236145724e83cdb6722df865babc6f4604b
78,76561198294321383,kiko,offline,https://steamcommunity.com/profiles/7656119829...,15,2,76905,990,76838,1773017686,a236d9ed940a8200157a3b4e608c687c88676d35
79,76561198737639629,Marrulis,offline,https://steamcommunity.com/id/skibidithiago/,6,1,2444,1485,2444,1773002284,eef7f71860b66ccf961601a0529f5ef67ebcbc3f
80,76561199524697526,Asilhann,online,https://steamcommunity.com/profiles/7656119952...,0,1,5409,3721,5359,1773016245,862261b7537dd5d9f8d9453ac1b710f0fe89c668
81,76561198760176726,kise,offline,https://steamcommunity.com/profiles/7656119876...,1,1,2708,595,2708,1773013043,31411213c35d1a4f61bd7cd5744e615eeff94f37
82,76561198761708087,__Kyok1__,offline,https://steamcommunity.com/profiles/7656119876...,7,3,2187,480,2187,1773012888,972a55e513a47604991a2bc7b6d003274c0138cb
83,76561199852201395,CRASHOUT...YN,offline,https://steamcommunity.com/profiles/7656119985...,0,1,2191,154,2127,1773015313,8c0f31e3bb2e21c841b564e8ac5fcd7abbb2d834
84,76561199141776571,Gael,offline,https://steamcommunity.com/id/owqg12389hcf/,48,13,5569,0,5569,1764971396,0b9e2595817fb81d038221dbb340981050c5d2d4
85,76561199218678475,djsifanis13,offline,https://steamcommunity.com/profiles/7656119921...,0,1,3696,2377,3672,1773014636,17983b4c687a8bf9bca407b01122a27521a961d8
86,76561198780158932,°%Ni§ki||€r%°,offline,https://steamcommunity.com/id/NIcs2/,14,1,10357,1251,10314,1773015465,d238ee73e125252e4a4ab5cc0ae3982df5af5c96
87,76561199725808094,π2shock,offline,https://steamcommunity.com/profiles/7656119972...,0,1,31801,282,31801,1772895506,3742140c2ac9ef330beaac45d21ce75f498d8c79
88,76561199840727182,Lycan,offline,https://steamcommunity.com/profiles/7656119984...,36,7,2094,0,2094,1767193490,e83f4ec04f3c513919c5766cdf6650e89719f161
89,76561198751088673,dayling,offline,https://steamcommunity.com/profiles/7656119875...,0,1,4762,1280,4762,1773011857,f929adb65687e7d2256aea1a1f2666cae0e3e1bc
90,76561198772644415,TURBO X,in-game,https://steamcommunity.com/profiles/7656119877...,1,1,3939,723,3874,1773019112,583c14f9c3b97681895cd2cb0b305568649ee895
91,76561199728263391,FortniteGamer69,offline,https://steamcommunity.com/profiles/7656119972...,16,3,1153,1153,1031,1773019351,d21b51997ec32ba0ea58966b949fc37c8dfa9411
92,76561199683914719,♥♥♥♥,offline,https://steamcommunity.com/profiles/7656119968...,3,1,39108,629,39108,1773011805,5aa4bf3051b44a2c22deff3567d14f214ccdeef0
93,76561198003445248,MASTER YODA,offline,https://steamcommunity.com/id/czaikowski/,0,4,293896,938,293811,1773016843,256318f5511de85ba4c4da2ebfc603d02c222cf2
94,76561199103962005,srta.septum,offline,https://steamcommunity.com/id/srta_septum/,0,1,4637,90,4637,1772759900,5dfd94c437407cb38707dbd11e3e94da0ba66747
95,76561199316669200,SY-TEAM DARK KX,offline,https://steamcommunity.com/profiles/7656119931...,14,1,16892,1344,16815,1773018452,818aa7b428dbcb7ebe0862a8ab8709c6e76bac0e
96,76561199221849181,muxypk,offline,https://steamcommunity.com/profiles/7656119922...,0,1,14421,2153,14421,1773007632,c26c19b0c1d0c6cb8bf88cd0fb245c67d19249d4
97,76561198739737840,Senna,online,https://steamcommunity.com/id/zxsenna/,0,1,12265,6982,12265,1773011287,e62f1637ec66f27e36714430e8ef8032decee7cb
98,76561198733329872,opsec,online,https://steamcommunity.com/id/idoonetapsallday...,0,1,4684,4726,4602,1773020147,50746a3eccc2b005b9da8ec13e19d283a0c0a124
99,76561198057703630,Pav_Low,offline,https://steamcommunity.com/profiles/7656119805...,0,1,93459,732,93459,1773011297,451a926cf9b6d1991bceea2d9c530ac9833679e6

In [ ]:
volvo_df[['author']]

                                               author
0   {'steamid': '76561199564706967', 'personaname'...
1   {'steamid': '76561198357954126', 'personaname'...
2   {'steamid': '76561199198269680', 'personaname'...
3   {'steamid': '76561199575895071', 'personaname'...
4   {'steamid': '76561198962608511', 'personaname'...
5   {'steamid': '76561197983839937', 'personaname'...
6   {'steamid': '76561198740600763', 'personaname'...
7   {'steamid': '76561199522542837', 'personaname'...
8   {'steamid': '76561199467143263', 'personaname'...
9   {'steamid': '76561198451518521', 'personaname'...
10  {'steamid': '76561198895145380', 'personaname'...
11  {'steamid': '76561198085689254', 'personaname'...
12  {'steamid': '76561198334772650', 'personaname'...
13  {'steamid': '76561198754801526', 'personaname'...
14  {'steamid': '76561199027422987', 'personaname'...
15  {'steamid': '76561199171265414', 'personaname'...
16  {'steamid': '76561198734161778', 'personaname'...
17  {'steamid': '76561199506317097', 'personaname'...
18  {'steamid': '76561199130647190', 'personaname'...
19  {'steamid': '76561198735921547', 'personaname'...
20  {'steamid': '76561199810621845', 'personaname'...
21  {'steamid': '76561199047008433', 'personaname'...
22  {'steamid': '76561198731443303', 'personaname'...
23  {'steamid': '76561198752765560', 'personaname'...
24  {'steamid': '76561198731168214', 'personaname'...
25  {'steamid': '76561198426811185', 'personaname'...
26  {'steamid': '76561199835966279', 'personaname'...
27  {'steamid': '76561198413672931', 'personaname'...
28  {'steamid': '76561198744541314', 'personaname'...
29  {'steamid': '76561198761886440', 'personaname'...
30  {'steamid': '76561199115563261', 'personaname'...
31  {'steamid': '76561198746482224', 'personaname'...
32  {'steamid': '76561199018384229', 'personaname'...
33  {'steamid': '76561199833786992', 'personaname'...
34  {'steamid': '76561199618905252', 'personaname'...
35  {'steamid': '76561198790574152', 'personaname'...
36  {'steamid': '76561198215264275', 'personaname'...
37  {'steamid': '76561198783659430', 'personaname'...
38  {'steamid': '76561199767562921', 'personaname'...
39  {'steamid': '76561198300819340', 'personaname'...
40  {'steamid': '76561199843212247', 'personaname'...
41  {'steamid': '76561199541712260', 'personaname'...
42  {'steamid': '76561199802204517', 'personaname'...
43  {'steamid': '76561199094374223', 'personaname'...
44  {'steamid': '76561199831097078', 'personaname'...
45  {'steamid': '76561197985321476', 'personaname'...
46  {'steamid': '76561199016173400', 'personaname'...
47  {'steamid': '76561199219280974', 'personaname'...
48  {'steamid': '76561198832052021', 'personaname'...
49  {'steamid': '76561199000823598', 'personaname'...
50  {'steamid': '76561199036544880', 'personaname'...
51  {'steamid': '76561199507242270', 'personaname'...
52  {'steamid': '76561199017378509', 'personaname'...
53  {'steamid': '76561199505205358', 'personaname'...
54  {'steamid': '76561199250001685', 'personaname'...
55  {'steamid': '76561199505756139', 'personaname'...
56  {'steamid': '76561199187216717', 'personaname'...
57  {'steamid': '76561198784575029', 'personaname'...
58  {'steamid': '76561199497299216', 'personaname'...
59  {'steamid': '76561198849484798', 'personaname'...
60  {'steamid': '76561199229653458', 'personaname'...
61  {'steamid': '76561198740048386', 'personaname'...
62  {'steamid': '76561199803191386', 'personaname'...
63  {'steamid': '76561198364474933', 'personaname'...
64  {'steamid': '76561199613122828', 'personaname'...
65  {'steamid': '76561198754783774', 'personaname'...
66  {'steamid': '76561198760222212', 'personaname'...
67  {'steamid': '76561199564030911', 'personaname'...
68  {'steamid': '76561199225053422', 'personaname'...
69  {'steamid': '76561197960628822', 'personaname'...
70  {'steamid': '76561199235041655', 'personaname'...
71  {'steamid': '76561198383648864', 'personaname'...
72  {'steamid': '76561198777927653', 'personaname'...
73  {'steamid': '76561198755382043', 'personaname'...
74  {'steamid': '76561198752743610', 'personaname'...
75  {'steamid': '76561199683693234', 'personaname'...
76  {'steamid': '76561198737286209', 'personaname'...
77  {'steamid': '76561199760071775', 'personaname'...
78  {'steamid': '76561198294321383', 'personaname'...
79  {'steamid': '76561198737639629', 'personaname'...
80  {'steamid': '76561199524697526', 'personaname'...
81  {'steamid': '76561198760176726', 'personaname'...
82  {'steamid': '76561198761708087', 'personaname'...
83  {'steamid': '76561199852201395', 'personaname'...
84  {'steamid': '76561199141776571', 'personaname'...
85  {'steamid': '76561199218678475', 'personaname'...
86  {'steamid': '76561198780158932', 'personaname'...
87  {'steamid': '76561199725808094', 'personaname'...
88  {'steamid': '76561199840727182', 'personaname'...
89  {'steamid': '76561198751088673', 'personaname'...
90  {'steamid': '76561198772644415', 'personaname'...
91  {'steamid': '76561199728263391', 'personaname'...
92  {'steamid': '76561199683914719', 'personaname'...
93  {'steamid': '76561198003445248', 'personaname'...
94  {'steamid': '76561199103962005', 'personaname'...
95  {'steamid': '76561199316669200', 'personaname'...
96  {'steamid': '76561199221849181', 'personaname'...
97  {'steamid': '76561198739737840', 'personaname'...
98  {'steamid': '76561198733329872', 'personaname'...
99  {'steamid': '76561198057703630', 'personaname'...

In [ ]:
#volvo_df.to_csv('CS_2_reviews_df.csv')

In [ ]:
# Ограничения Allowed poll rate - 1 request per second for most requests, 1 request per 60 seconds for the *all* requests.
API_BASE_SPY = "https://steamspy.com/api.php"

spy_pages = [0,1,2,3]

Endpoint_spy = f"{API_BASE_SPY}request=all&page=" # список всех игр

SPY_params = {
    "request": "all",
    "page": 0 }

response_spy = requests.get(API_BASE_SPY, params = SPY_params)
print(response_spy)
data_spy = response_spy.json()

print(type(data_spy))

<Response [200]>
<class 'dict'>

In [ ]:
# Тут id игр с нулевой страницы
data_spy.keys()

dict_keys(['730', '1172470', '578080', '1623730', '440', '1938090', '1063730', '2358720', '271590', '550', '304930', '1599340', '236390', '2246340', '553850', '230410', '1245620', '105600', '2694490', '431960', '1086940', '291550', '4000', '1085660', '359550', '252490', '552990', '346110', '413150', '242760', '1491000', '238960', '218620', '291480', '901583', '899770', '340', '1091500', '381210', '990080', '438100', '292030', '945360', '1097150', '49520', '227300', '892970', '739630', '444090', '1203220', '320', '70', '582010', '227940', '252950', '108600', '1966720', '1174180', '1517290', '1240440', '648800', '386360', '444200', '10', '240', '3164500', '755790', '400', '1222670', '550650', '322330', '239140', '477160', '251570', '100', '1665460', '417910', '433850', '594650', '814380', '1116170', '220', '107410', '1326470', '219990', '255710', '261550', '8930', '304050', '289070', '377160', '532210', '2186680', '1238810', '3241660', '221100', '526870', '1089350', '632360', '1811260', '204360', '218230', '72850', '394360', '489830', '322170', '1446780', '224260', '203160', '275850', '367520', '301520', '767560', '2050650', '466240', '284160', '278360', '264710', '80', '370910', '40', '275390', '2881650', '311210', '333930', '1172620', '22380', '250900', '700330', '10180', '582660', '1229490', '1046930', '1426210', '2195250', '2183900', '883710', '219640', '306130', '244210', '268500', '1794680', '1818750', '242050', '30', '236850', '363970', '253710', '379720', '273350', '1782210', '844870', '601150', '1286830', '365670', '319630', '1293830', '1145360', '671860', '427520', '221380', '231430', '813820', '594570', '391540', '976730', '646570', '588650', '268910', '439700', '500', '1118200', '620', '1551360', '1049590', '380', '360', '779340', '233450', '782330', '223710', '677620', '513710', '1677740', '109600', '420', '397900', '698780', '435150', '1100600', '1604030', '534380', '766570', '548430', '294100', '273110', '868270', '863550', '1237970', '555570', '10190', '424840', '2669320', '518790', '365590', '223470', '241930', '346900', '3240220', '440900', '374320', '304390', '1868140', '208090', '48700', '2630', '12210', '1144200', '113400', '1332010', '206420', '380600', '225540', '285800', '286690', '223750', '1593500', '386180', '1238840', '812140', '1721470', '960090', '55230', '262060', '761890', '2001120', '281990', '252130', '211820', '8190', '6060', '508440', '115300', '42910', '39210', '1222680', '351940', '1250', '2623190', '323190', '1716740', '813780', '630', '57300', '395170', '20920', '212680', '504370', '286160', '311690', '355840', '1145350', '1366800', '1196590', '613100', '1172380', '202970', '304430', '3590', '1260320', '33930', '212500', '457140', '620980', '1222140', '1817070', '205100', '24240', '1506830', '871720', '962130', '356190', '274190', '234140', '8500', '552520', '7670', '760160', '1203620', '270880', '601510', '397540', '12120', '236870', '674940', '884660', '701160', '1832640', '208650', '48000', '2379780', '298110', '42710', '200710', '203770', '1903340', '244850', '1366540', '2709570', '201270', '389730', '10090', '1259420', '261640', '220200', '1142710', '265630', '219150', '418460', '312990', '211500', '506540', '20900', '552500', '1057090', '359320', '214950', '9480', '245170', '207610', '35450', '285900', '232090', '42680', '918570', '1771300', '447040', '200510', '361420', '33900', '209080', '307780', '335240', '403640', '99900', '1289310', '287700', '460930', '219740', '96000', '35720', '387990', '880940', '409710', '686810', '418370', '50130', '1454400', '379430', '274170', '232770', '1363080', '585690', '289650', '17410', '4560', '2479810', '233130', '1056960', '976310', '202990', '355180', '678950', '1151340', '299360', '213670', '262410', '224600', '368230', '3097560', '335300', '233860', '391720', '240720', '838350', '238320', '282070', '412020', '1158310', '2567870', '265930', '214490', '362890', '438740', '617290', '588430', '1943950', '203140', '12100', '905370', '1056640', '1942280', '238460', '38400', '881020', '65800', '204880', '235460', '581320', '34330', '387290', '728880', '391220', '8870', '372000', '239030', '629760', '646910', '367500', '13520', '967050', '2399830', '648350', '471710', '1372880', '524220', '305620', '475150', '47870', '629520', '282440', '436150', '1304930', '550900', '33230', '427730', '221040', '1274570', '1222700', '1468810', '287390', '570940', '1272080', '316010', '105450', '1167630', '11020', '12200', '881100', '1313140', '261570', '1361210', '221910', '238090', '242720', '1250410', '644930', '641990', '1254120', '222880', '1569040', '201790', '203290', '2670630', '286570', '787860', '466560', '207140', '1092790', '431240', '248570', '107100', '209000', '24960', '848450', '286940', '740130', '17390', '530700', '2622380', '220240', '1217060', '1248130', '437900', '635260', '259080', '414340', '42700', '108710', '55100', '1520470', '644560', '1263850', '407530', '774171', '279720', '201810', '319510', '1888160', '674020', '310950', '952060', '1466860', '949230', '388410', '1904540', '544810', '611500', '50', '1408720', '310560', '1845910', '254700', '1029690', '12220', '308040', '815370', '470220', '302830', '242920', '236110', '383870', '1399780', '1237950', '312660', '502500', '632470', '200260', '393380', '40800', '303390', '280', '783770', '212070', '110800', '50300', '41070', '1284210', '35700', '485510', '210770', '282140', '495420', '323580', '225260', '2835570', '464920', '493340', '9900', '7940', '343710', '504230', '394510', '265590', '1128810', '325610', '1643320', '204450', '63380', '268420', '482730', '360970', '22370', '349040', '204100', '823130', '1184370', '640820', '47890', '637650', '703080', '460950', '35140', '50620', '337000', '433340', '238010', '527230', '39120', '307690', '2054970', '266840', '645630', '1790600', '300', '368260', '389570', '736590', '1637320', '409720', '975370', '15620', '1371980', '993090', '476480', '65930', '2215430', '1277400', '3132990', '606150', '602960', '342200', '1824220', '55150', '8980', '900883', '312530', '1139900', '1343400', '738060', '893520', '234650', '744900', '314160', '1364780', '9010', '554620', '368500', '17470', '204300', '630100', '750920', '436520', '1659040', '788100', '858820', '680420', '678960', '1611910', '206440', '613010', '424280', '212160', '1030830', '365450', '302510', '22330', '1687950', '113020', '238370', '3070070', '977950', '6860', '1057240', '511470', '268050', '389430', '289130', '488790', '493520', '546560', '439190', '67370', '845070', '453480', '633230', '32370', '476600', '1404210', '1557740', '1619450', '683320', '2551020', '1536610', '386940', '346010', '924970', '349700', '208140', '206500', '57690', '2322010', '274940', '412220', '1290000', '1286680', '39500', '872790', '291650', '17330', '1533390', '606280', '10500', '1476970', '1262580', '246620', '319830', '324800', '341800', '322500', '939960', '239820', '509980', '364360', '492720', '12110', '460790', '627690', '1213210', '569480', '2021910', '242860', '239160', '391460', '636480', '2100', '21690', '228280', '629730', '2420510', '113420', '706990', '269210', '304240', '621060', '48190', '638970', '24010', '228380', '327690', '417860', '1058020', '1262350', '582160', '287450', '582500', '22320', '519860', '442080', '704270', '40990', '1627140', '612880', '638070', '3146520', '537180', '232890', '6000', '1049410', '1343370', '1238860', '961200', '2527500', '102600', '870780', '24980', '312520', '285190', '202170', '235600', '34030', '459820', '47810', '280790', '1313860', '2280', '637090', '690790', '704850', '424370', '851850', '243470', '491950', '1384160', '2622000', '1061910', '247080', '392110', '47830', '214420', '9340', '438040', '752590', '736220', '933110', '24200', '304670', '228200', '233720', '1483870', '692850', '1241100', '15100', '1282100', '287290', '1225330', '4920', '1515950', '19900', '979690', '130', '809960', '232050', '47790', '253980', '292730', '774361', '34270', '4500', '251060', '32470', '837470', '834910', '454650', '1238820', '1284410', '323470', '1089980', '1147560', '214560', '225080', '237930', '96100', '113200', '2310', '599140', '1840', '65980', '373420', '1621690', '311860', '1089090', '942970', '41500', '1778820', '17080', '1522820', '23310', '487220', '34440', '4570', '2322560', '2344520', '10680', '6880', '216150', '443110', '378540', '527430', '753640', '334210', '206480', '583950', '921630', '215080', '65790', '311340', '535930', '332070', '414700', '270150', '292910', '447020', '17300', '1282730', '32800', '102500', '8850', '899440', '418240', '207230', '20570', '17460', '383150', '224760', '1178830', '510840', '2012510', '297000', '1151640', '334230', '418070', '364470', '1190000', '601430', '263500', '4700', '39140', '675010', '220440', '240320', '544730', '337320', '350640', '2231450', '552100', '1475810', '427270', '392160', '346330', '3910', '1380400', '805550', '41000', '1284190', '2064650', '56437', '585420', '1562430', '1987080', '666220', '245620', '529340', '657200', '209160', '6850', '1388770', '603850', '32430', '253900', '1113000', '1016920', '955050', '1929610', '1850570', '2096610', '446800', '250400', '209170', '1211020', '1296830', '410320', '261110', '208580', '775500', '447820', '1599600', '475550', '257510', '474960', '237110', '444640', '843380', '560130', '4760', '568220', '202750', '257350', '1676130', '34870', '224540', '816020', '699130', '681660', '462780', '34460', '448510', '1129580', '1307550', '460920', '55110', '278080', '996580', '231060', '108800', '1094520', '673950', '747660', '6910', '239350', '360430', '215280', '1030840', '673130', '377300', '323850', '2552430', '823500', '841370', '204340', '794260', '299460', '2680010', '1755910', '1266680', '265550', '246900', '253960', '450390', '920210', '17480', '249130', '1017180', '26800', '1515210', '1147550', '640590', '434650', '1774580', '431730', '780310', '261030', '226840', '374040', '1328670', '1044720', '668580', '544750', '972660', '1150690'])

In [ ]:
df_spy_data = pd.DataFrame([data_spy['730']])

In [ ]:
df_spy_data

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
0,730,Counter-Strike: Global Offensive,Valve,Valve,,7642084,1173003,0,"100,000,000 .. 200,000,000",33852,708,6645,301,0,0,0,1013936